;==================================================================================
;==   User Variables   ============================================================
;==================================================================================

[Variables]
	MainColour  =FF8000
	FontColour  =FCFCFC
	PlayerName  =Spotify
	Location    =Poynton
	Unit        =C
	Disk1       =C
	Disk2       =N
	Disk3       =O

	LocationCalendar =2
	LocationClock    =1
	LocationDisk1    =4
	LocationDisk2    =0
	LocationDisk3    =0
	LocationMusic    =-2
	LocationNetwork  =0
	LocationPower    =-1
	LocationSystem   =3
	LocationWeather  =5

	; LocationY0 is only used to null the placement
	LocationY0 =0
	LocationY1 =#ClockH#
	LocationY2 =#CalenderH#
	LocationY3 =#SystemH#
	LocationY4 =#DiskH#
	LocationY5 =#WeatherH#
	LocationY6 =#DiskH#
	LocationY7 =0
	LocationY8 =0
	LocationY9 =0
	LocationY-1=#PowerH#
	LocationY-2=#MusicH#
